# Generated by Django 6.1.1 on 2026-09-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('exchange', models.CharField(max_length=16)),
                ('segment', models.CharField(default='EQ', max_length=16)),
                ('instrument_type', models.CharField(default='EQUITY', max_length=16)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default='0.05', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(max_length=32)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='marketdata.instrument')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'timestamp'], name='marketdata__instrum_089b1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timeframe', 'timestamp', 'source'), name='uniq_candle_bar')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentBrokerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=32)),
                ('broker_symbol', models.CharField(max_length=64)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_mappings', to='marketdata.instrument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('broker', 'broker_symbol'), name='uniq_broker_symbol'), models.UniqueConstraint(fields=('instrument', 'broker'), name='uniq_instrument_per_broker')],
            },
        ),
    ]
