# Generated by Django 6.1.1 on 2026-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='sector',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
