# Generated by Django 6.1.1 on 2026-09-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('range', 'Range'), ('breakout', 'Breakout'), ('trend_following', 'Trend Following'), ('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('custom', 'Custom')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('entry_rules', models.JSONField()),
                ('exit_rules', models.JSONField()),
                ('stop_loss', models.JSONField()),
                ('target', models.JSONField()),
                ('trailing_stop', models.JSONField(blank=True, null=True)),
                ('position_sizing', models.JSONField()),
                ('max_positions', models.PositiveIntegerField(default=1)),
                ('max_capital_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('min_risk_reward', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['strategy', '-version_number'],
                'constraints': [models.UniqueConstraint(fields=('strategy', 'version_number'), name='uniq_strategy_version')],
            },
        ),
    ]
